name: CI

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  nix-flake-check:
    name: nix flake check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir:
          - ./
          - ./nodejs
          - ./simple-flake
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          # Helps avoid rate limiting
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check ${{ matrix.dir }} -L --all-systems --keep-going

  nix-develop:
    name: test nix dev shell
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir:
          - ./
          - ./nodejs
          - ./simple-flake
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          # Helps avoid rate limiting
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix develop ${{ matrix.dir }} -Lc true
